### PR TITLE
Frankreed/genericized auth error

### LINKED ISSUE #267: Login saying "User not found" and "Incorrect password" could be used to discover which user exists in the database and/or brute force the password
Make it so it says "Incorrect authentication" or some other more generic errors

### PR DESCRIPTION
**Pull request by FrankreedX**
closes #267

### CODE REVIEW

File: app/(auth)/signup.js [hunk 1]
```diff
@@ -40,6 +41,9 @@ export default function SignUp() {
       if (password !== passwordCheck) {
         throw "Passwords don't match";
       }
+      if (!email.endsWith("@oregonstate.edu")) {
+        throw "Only @oregonstate.edu emails are allowed at this time.";
+      }
```
Comment (Gehrkej) [inline app/(auth)/signup.js:46]: I think this is good for the short term but we will want to make sure others are aware of this so when we expand to other teams we can remove this

File: app/(auth)/signin.js [hunk 2]
```diff
@@ -46,7 +46,7 @@ export default function SignIn() {
         await signInWithEmailAndPassword(auth, email, password);
       } catch (e) {
         console.log(e);
-        showDialog("Error", getErrorString(e));
+        showDialog("Error", "Authentication Error"); //maybe could be more specific about only invalid email and invalid password errors
```
Comment (Gehrkej) [inline app/(auth)/signin.js:49]:
```suggestion
        showDialog("Error", "Authentication Error. Invalid Email or Password was entered."); 
```
^^ I am unsure of what other errors could be thrown. Additionally, this could just be something we add into the firebaseErrors object in constants.

**Review by Gehrkej — COMMENTED** [review]
Overall looks good to me, I like that you caught this security risk as well. My suggestion might be too broad for the error handling but I think just replacing the strings in firebaseErrors could be good. LMK what you think though

**Review by solderq35 — CHANGES_REQUESTED** [review]
I think we also need to remove "Incorrect password" message from user profile settings (changing password)

image

**Comment by solderq35** [comment]
EDIT: Also not sure if it's a good idea to hide "incorrect password" in general. If a specific email (e.g. coach's email) is already known anyways, obfuscating "incorrect password" message will not fool them.

**Comment by solderq35** [comment]
Colby suggested changing the username and password errors to "Incorrect username / password"

**Comment by FrankreedX** [comment]
> I think we also need to remove "Incorrect password" message from user profile settings (changing password)
> 
> image

I think this one should stay, but it'll be kinda jank because it returns the same error as the login screen

File: Constants.js [hunk 3]
```diff
@@ -48,10 +48,10 @@ const prettyRole = {
 
 const firebaseErrors = {
   "auth/email-already-in-use": "Email is already in use",
-  "auth/invalid-email": "Invalid email",
+  "auth/invalid-email": "Incorrect username / password",
```
Comment (Gehrkej) [inline Constants.js:51]: Should this be like this since we use email and not username?

```suggestion
  "auth/invalid-email": "Incorrect email / password",
```

File: Constants.js [hunk 4]
```diff
@@ -48,10 +48,10 @@ const prettyRole = {
...
   "auth/weak-password": "Password is too weak",
   "auth/user-not-found": "User not found",
-  "auth/wrong-password": "Incorrect password",
+  "auth/wrong-password": "Incorrect username / password",
```
Comment (Gehrkej) [inline Constants.js:54]: same thing here.
```suggestion
  "auth/wrong-password": "Incorrect email / password",
```

**Review by Gehrkej — CHANGES_REQUESTED** [review]
using 'username' in the error message might cause some confusion since the user is being prompted for an email

**Comment by Gehrkej** [comment]
> > I think we also need to remove "Incorrect password" message from user profile settings (changing password)
> > image
> 
> I think this one should stay, but it'll be kinda jank because it returns the same error as the login screen

I would agree this one is find to stay. If a user is already in their account than they should be able to get more specific feedback as malicious users or hackers probably would already have the password if they already got access to the account.

**Review by Gehrkej — APPROVED** [review]
LGTM 👍

File: Constants.js [hunk 5]
```diff
@@ -48,10 +48,10 @@ const prettyRole = {
 
 const firebaseErrors = {
   "auth/email-already-in-use": "Email is already in use",
-  "auth/invalid-email": "Invalid email",
+  "auth/invalid-email": "Incorrect email / password",
```
Comment (solderq35) [inline Constants.js:51]: Is this being used anymore?

**Review by solderq35 — APPROVED** [review]
I think the "auth/invalid-email" constant is not being used (as mentioned in other comment). Other than that it looks good. I tested and confirmed that "Invalid password" is shown in profile settings, and that only emails with `@oregonstate.edu` domains were allowed to sign up.

File: Constants.js (hunk 5 above)
Comment (FrankreedX) [reply Constants.js:51]: This is tripped when an email that haven't been signed up is entered in signin.js. It's not explicitly mentioned but the error is returned by firebase

Comment (FrankreedX) [reply Constants.js:51]: But it's a good point because it's hard to know which is tripped and which is not. Only unit tests can tell
